# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# iOS 15.1 minimum required by React Native 0.82
platform :ios, '15.1'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'NitroVtoExample' do
  config = use_native_modules!

  # Use local NitroVto podspec (which includes Filament dependency)
  pod 'NitroVto', :path => '../../node_modules/@alaneu/react-native-nitro-vto'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Required for Filament C++20 and link Filament libraries
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
      end
      
      # Link Filament libraries for NitroVto target
      if target.name == 'NitroVto'
        target.build_configurations.each do |config|
          config.build_settings['LIBRARY_SEARCH_PATHS'] ||= ['$(inherited)']
          config.build_settings['LIBRARY_SEARCH_PATHS'] << '"$(PODS_ROOT)/Filament/lib/universal"'
          
          config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)']
          filament_libs = %w[filament backend filabridge filaflat geometry ibl utils gltfio_core dracodec uberarchive stb image ktxreader basis_transcoder uberzlib zstd shaders smol-v]
          filament_libs.each do |lib|
            config.build_settings['OTHER_LDFLAGS'] << "-l#{lib}"
          end
        end
      end
    end
  end
end
